[package]
name = "rapira_fuzz"
version = "0.0.0"
publish = false
edition = "2024"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"
rapira_http = { path = "../crates/plugins/http" }

[workspace]
members = ["."]

[[bin]]
name = "multipart"
path = "fuzz_targets/multipart.rs"
test = false
doc = false
bench = false
